# Generated by Django 2.2.6 on 2019-11-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191112_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': '联系信息', 'verbose_name_plural': '联系信息'},
        ),
    ]
