# Generated by Django 2.2.6 on 2019-11-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20191029_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': '博客作者', 'verbose_name_plural': '博客作者'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': '博客目录', 'verbose_name_plural': '博客目录'},
        ),
    ]
